#+TITLE: Simple web application to manage reservations for Italian Dinner

* Introduction

This is a simplistic set of CGI scripts adapted for my web host and as a
learning exercise to see how much features and ease-of-use a web framework
deliver.

See also [[file+emacs:app/gestion/index.org][usage instructions and checklists (in French)]].

* Deployment

Use the ~deploy.sh~ script like this:
#+begin_src shell :exports code
  ./deploy.sh 'user@host' 'username' 'groupname' 'https://host' 'prefix_folder' 'deploy_folder' ['admin_user' 'admin_pw']
#+end_src

- ~user@host~ :: anything that `ssh` accepts.
- ~username~ and ~groupname~ :: CGI scripts are only executed if they belong
  to a specific user/group that does not correspond to the user/group of the
  system where development happens.  These parameters set the user/group in
  the destination.
- ~prefix_folder/destination_folder~ :: where to deploy (relative to the
  SSH host, not necessarily the path typed in your browser)
- ~admin_user~ and ~admin_pw~ :: the administrative interface should be
  protected by authentication.  If the parameters are given, HTTP basic
  authentication is setup in that folder.

Then configure the application
- upload images for the dishes to =prefix_folder/deploy_folder/gestion/=, e.g.
  + [[https://www.vecteezy.com/vector-art/3736403-spaghetti-bolognese-with-tomato-sauce][spaghetti bolognese with tomato sauce]]
    #+begin_example
      <a href="https://www.vecteezy.com/free-vector/cartoon">Cartoon Vectors by Vecteezy</a>
    #+end_example
  + [[https://www.vecteezy.com/vector-art/965991-spaghetti-meal-set][spaghetti meal set]]
    #+begin_example
      <a href="https://www.vecteezy.com/free-vector/cartoon">Cartoon Vectors by Vecteezy</a>
    #+end_example
  + [[https://www.vecteezy.com/search?qterm=croquette-cheese&content_type=vector][cheese croquette]]
    #+begin_example
      <a href="https://www.vecteezy.com/free-vector/croquette">Croquette Vectors by Vecteezy</a>
    #+end_example
  + [[https://www.vecteezy.com/vector-art/10456729-vector-contour-drawing-of-mozzarella-cheese-slices-on-a-white-background][mozzarella cheese]]
    #+begin_example
      <a href="https://www.vecteezy.com/free-vector/black">Black Vectors by Vecteezy</a>
    #+end_example
  + [[https://www.vecteezy.com/vector-art/150043-free-sweet-food-line-icon-vector][sweet food]]
    #+begin_example
      <a href="https://www.vecteezy.com/free-vector/vector">Vector Vectors by Vecteezy</a>
    #+end_example
- edit =prefix_folder/deploy_folder/configuration.json= on your webserver (cf
  [[file+emacs:app/config.py][app/config.py]]).
- Put up the dynamic or static input form

** Dynamic input form
There is a [[file+emacs:input-form/][Fable/Elmish application]] that is deployed next to these CGI scripts
that generates an input form dynamically.
#+begin_example
  <div id="elmish-app"></div>
  <script>
    const ACTION_DEST = 'https://your-host/.../post_reservation.cgi';
    const CONCERT_DATE = '1234-56-78';</script>
  <script defer src="http://your-host/.../demo.???.js"></script>
  <script defer src="http://your-host/.../vendors.???.js"></script>
#+end_example
** Static input form
Host an HTML form that will =POST= its content to the =post_reservation.cgi=
script:
#+begin_example
  <form action="https://YOUR_HOST/DEPLOYMENT_DIR/post_reservation.cgi" method="POST">
    <input name="date" type="hidden" value="2099-01-01">
    <label for="name">Nom:</label><br>
    <input id="name" style="width: 100%;" name="name" required="required" type="text" placeholder="Il est obligatoire de saisir votre nom"><br>
    <label for="email">Email:</label><br>
    <input id="email" style="width: 100%;" name="email" required="required" type="email" placeholder="Nous pourrions avoir besoin de votre email pour le tracing"><br>
    <label for="places">Nombre de convives:</label><br>
    <input id="places" name="places" type="number"><p></p>
    <ul>
      <li>Entrées
        <ol>
        <li><label style="display: inline-block; width: 14em;" for="assiettes">Assiette italienne (8€):</label> <input id="assiettes" style="width: 5em;" max="20" min="0" name="assiettes" type="number" value="0"></li>
        <li><label style="display: inline-block; width: 14em;" for="fondus">Croquettes au fromage (8€):</label> <input id="fondus" style="width: 5em;" max="20" min="0" name="fondus" type="number" value="0"></li>
        </ol>
      </li>
      <li>Plats
        <ol>
        <li><label style="display: inline-block; width: 14em;" for="bolo">Spaghetti Bolognaise (10€):</label> <input id="bolo" style="width: 5em;" max="20" min="0" name="bolo" type="number" value="0"></li>
        <li><label style="display: inline-block; width: 14em;" for="scampis">Spaghetti aux scampis (15€):</label> <input id="scampis" style="width: 5em;" max="20" min="0" name="scampis" type="number" value="0"></li>
        </ol>
      </li>
      <li>Desserts
        <ol>
        <li><label style="display: inline-block; width: 14em;" for="tiramisu">Tiramisu Maison (5€):</label> <input id="tiramisu" style="width: 5em;" max="20" min="0" name="tiramisu" type="number" value="0"></li>
        <li><label style="display: inline-block; width: 14em;" for="tranches">Tranche Napolitaine (5€):</label> <input id="tranches" style="width: 5em;" max="20" min="0" name="tranches" type="number" value="0"></li>
        </ol>
      </li>
    </ul>
    <div style="display: grid;">
      <div style="grid-row: 1; grid-column: 1;"><input id="gdpr_accepts_use" name="gdpr_accepts_use" type="checkbox" value="true"></div>
      <div style="grid-row: 1; grid-column: 2;"><label for="gdpr_accepts_use">J’autorise la Société Royale d’Harmonie de Braine-l’Alleud à utiliser mon adresse email pour m’avertir de ses futures activités.</label></div>
    </div>
    <input type="submit" value="Confirmer">
  </form>
#+end_example

* Test mode
There are 3 dates for the dinner: 2 fake dates in 2099 and the real dates
in 2023.

The trick to be able to book dates for the fake dates is that the name must
start with ~Test~ and that the email address must end with ~@example.com~.

There are some automated tests in [[file+emacs:tests/tests.sh][this shell script]].  It exercises various
end-points and compares the HTML output with known good HTML output.  The
tests are unfortunately not real unit tests: they have to be run in sequence
as the state of one test is often assumed in the next test.

* Limitations
- No maximum number of seats per concert enforced.
- Minimal validation on name and email: we count on the fact that few people
  will find the form and that we will weed out fake registrations by seeing
  who pays.

* NixOS instructions
If you don't use [[https://direnv.net/][direnv]] to automatically activate your nix-shell, use this
command line (note that there are no quotes on purpose!):
#+begin_src shell :exports code
  nix-shell $(sed 's/use nix //' .envrc)
#+end_src

In the nix-shell:
1. See [[file+emacs:input-form/README.md][input-form README file]] to build the interactive menu selection form
2. Use the [[Deployment][Deployment instructions]]
