#+TITLE: Simple web application to manage reservation for gala concert

* Introduction

This is a simplistic set of CGI scripts adapted for my web host and as a
learning exercise to see how much features and ease-of-use a web framework
deliver.

See also [[file+emacs:app/gestion/index.org][usage instructions and checklists (in French)]].

* Deployment

Use the ~deploy.sh~ script like this:
#+begin_src shell :exports code
  ./deploy.sh 'user@host' 'username' 'groupname' 'destination_folder'
#+end_src

- ~user@host~ :: anything that =ssh= accepts.
- ~username~ and ~groupname~ :: CGI scripts are only executed if they belong
  to a specific user/group that does not correspond to the user/group of the
  system where development happens.  These parameters set the user/group in
  the destination.
- ~destination_folder~ :: where to deploy.

Host an HTML form that will =POST= its content to the =post_reservation.cgi=
script:
#+begin_example
  <form action="https://YOUR_HOST/DEPLOYMENT_DIR/post_reservation.cgi" method="POST">
    <div style="display: flex;">
      <select id="civility" name="civility">
        <option value="" selected="selected">???</option>
        <option value="mlle">Mlle</option>
        <option value="mme">Mme</option>
        <option value="mr">Mr</option>
      </select>
      <input id="first_name" name="first_name" type="text" placeholder="Prénom" style="width: 40%">
      <input id="last_name" name="last_name" type="text" placeholder="Nom de famille" required="required" style="width: 60%">
    </div>
    <input id="email" name="email" type="email" placeholder="Adresse email pour le suivi de votre commande" required="required" style="width: 100%;">
    <div style="display: grid;">
      <div style="grid-row: 1; grid-column: 1;"><input type="checkbox" id="gdpr_accepts_use" name="gdpr_accepts_use" value="true"></div>
      <div style="grid-row: 1; grid-column: 2;">
        <label for="gdpr_accepts_use">J'autorise la Société Royale d'Harmonie de Braine-l'Alleud à utiliser mon adresse email pour m'avertir de ses futures activités.</label>
      </div>
    </div>
    <input id="samedi" name="date" type="radio" value="2024-11-30" checked="checked"><label for="samedi">Samedi 30 novembre 2024 à 20h</label><br>
    <input id="dimanche" name="date" type="radio" value="2024-12-01"><label for="dimanche">Dimanche 1 décembre 2024 à 15h</label><br>
    <div style="display: grid;">
      <div style="grid-row: 1; grid-column: 1;">
        <label for="paying_seats">Places payantes (12€ en prévente; plus de 12 ans):</label>
      </div>
      <div style="grid-row: 1; grid-column: 2;">
        <input id="paying_seats" name="paying_seats" type="number" min="0" value="1" style="width: 5em;">
      </div>
      <div style="grid-row: 2; grid-column: 1;">
        <label for="free_seats">Places gratuites (moins de 12 ans):</label>
      </div>
      <div style="grid-row: 2; grid-column: 2;">
        <input id="free_seats" name="free_seats" type="number" min="0" value="0" style="width: 5em;">
      </div>
    </div>
    <input type="submit" value="Confirmer" style="width: 100%;">
  </form>
  <p>La Société Royale d'Harmonie de Braine-l'Alleud respecte votre vie
  privée. Les données de contact que vous nous communiquez dans ce formulaire
  seront uniquement utilisées dans le cadre de ce concert de Gala, à moins que
  vous nous donniez l'autorisation de les garder pour vous informer de nos
  concerts et autres fêtes dans le futur.
  <a href="mailto:info@srhbraine.be">Contactez-nous</a> pour demander d'être
  retiré de nos fichiers.</p>
#+end_example

* Test mode
There are 4 dates for the concert: 2 fake dates in 2099 and the 2 real dates
in 2024.

The trick to be able to book dates for the fake dates is that the last name
must start with ~Test~ and that the email address must end with
~@example.com~.

There are some automated test in [[file+emacs:tests/tests.sh][this shell script]].  It exercises various
end-points and compares the HTML output with known good HTML output.  The
tests are unfortunately not real unit tests: they have to be run in sequence
as the state of one test is often assumed in the next test.

* Limitations
- No maximum number of seats per concert enforced.
- Minimal validation on name and email: we count on the fact that few people
  will find the form and that we will weed out fake registrations by seeing
  who pays.
